<!-- 
RSS generated by JIRA (6.4.11#64026-sha1:78f6ec473a3f058bd5d6c30e9319c7ab376bdb9c) at Fri Dec 23 10:17:00 UTC 2016

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://jira.spring.io/si/jira.issueviews:issue-xml/SEC-2664/SEC-2664.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>Spring JIRA</title>
    <link>https://jira.spring.io</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.4.11</version>
        <build-number>64026</build-number>
        <build-date>25-08-2015</build-date>
    </build-info>

<item>
            <title>[SEC-2664]  ActiveDirectoryLdapAuthenticationProvider should wrap communication exceptions in InternalAuthenticationServiceException</title>
                <link>https://jira.spring.io/browse/SEC-2664</link>
                <project id="10040" key="SEC">Spring Security</project>
                    <description>&lt;p&gt;Jun 23, 2014 2:53:43 PM org.apache.catalina.core.StandardWrapperValve invoke&lt;br/&gt;
SEVERE: Servlet.service() for servlet &lt;span class=&quot;error&quot;&gt;&amp;#91;default&amp;#93;&lt;/span&gt; in context with path &lt;span class=&quot;error&quot;&gt;&amp;#91;/myapp&amp;#93;&lt;/span&gt; threw exception&lt;br/&gt;
org.springframework.ldap.CommunicationException: myazuread.cloudapp.net:389; nested exception is javax.naming.CommunicationException: myazuread.cloudapp.net:389 &lt;span class=&quot;error&quot;&gt;&amp;#91;Root exception is java.net.UnknownHostException: myazuread.cloudapp.net&amp;#93;&lt;/span&gt;&lt;br/&gt;
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:100)&lt;br/&gt;
	at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.bindAsUser(ActiveDirectoryLdapAuthenticationProvider.java:170)&lt;br/&gt;
	at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.doAuthentication(ActiveDirectoryLdapAuthenticationProvider.java:111)&lt;br/&gt;
	at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:61)&lt;br/&gt;
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)&lt;br/&gt;
	at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)&lt;br/&gt;
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:194)&lt;br/&gt;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&lt;br/&gt;
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)&lt;br/&gt;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&lt;br/&gt;
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)&lt;br/&gt;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&lt;br/&gt;
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)&lt;br/&gt;
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)&lt;br/&gt;
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)&lt;br/&gt;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)&lt;br/&gt;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)&lt;br/&gt;
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)&lt;br/&gt;
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)&lt;br/&gt;
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)&lt;br/&gt;
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)&lt;br/&gt;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)&lt;br/&gt;
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)&lt;br/&gt;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)&lt;br/&gt;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)&lt;br/&gt;
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)&lt;br/&gt;
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)&lt;br/&gt;
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)&lt;br/&gt;
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)&lt;br/&gt;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)&lt;br/&gt;
	at java.lang.Thread.run(Thread.java:744)&lt;br/&gt;
Caused by: javax.naming.CommunicationException: myazuread.cloudapp.net:389 &lt;span class=&quot;error&quot;&gt;&amp;#91;Root exception is java.net.UnknownHostException: myazuread.cloudapp.net&amp;#93;&lt;/span&gt;&lt;br/&gt;
	at com.sun.jndi.ldap.Connection.&amp;lt;init&amp;gt;(Connection.java:226)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapClient.&amp;lt;init&amp;gt;(LdapClient.java:136)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1608)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2698)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapCtx.&amp;lt;init&amp;gt;(LdapCtx.java:316)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:193)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:211)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)&lt;br/&gt;
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)&lt;br/&gt;
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)&lt;br/&gt;
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:307)&lt;br/&gt;
	at javax.naming.InitialContext.init(InitialContext.java:242)&lt;br/&gt;
	at javax.naming.ldap.InitialLdapContext.&amp;lt;init&amp;gt;(InitialLdapContext.java:153)&lt;br/&gt;
	at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider$ContextFactory.createContext(ActiveDirectoryLdapAuthenticationProvider.java:311)&lt;br/&gt;
	at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.bindAsUser(ActiveDirectoryLdapAuthenticationProvider.java:164)&lt;br/&gt;
	... 29 more&lt;br/&gt;
Caused by: java.net.UnknownHostException: myazuread.cloudapp.net&lt;br/&gt;
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)&lt;br/&gt;
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)&lt;br/&gt;
	at java.net.Socket.connect(Socket.java:579)&lt;br/&gt;
	at java.net.Socket.connect(Socket.java:528)&lt;br/&gt;
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:425)&lt;br/&gt;
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:208)&lt;br/&gt;
	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:368)&lt;br/&gt;
	at com.sun.jndi.ldap.Connection.&amp;lt;init&amp;gt;(Connection.java:203)&lt;br/&gt;
	... 43 more&lt;/p&gt;
</description>
                <environment>Ubuntu 12.04, Open JDK 7.0 </environment>
        <key id="58393">SEC-2664</key>
            <summary> ActiveDirectoryLdapAuthenticationProvider should wrap communication exceptions in InternalAuthenticationServiceException</summary>
                <type id="1" iconUrl="https://jira.spring.io/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="4" iconUrl="https://jira.spring.io/images/icons/priorities/minor.png">Minor</priority>
                        <status id="6" iconUrl="https://jira.spring.io/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="-1">Unassigned</assignee>
                                    <reporter username="pradeepagrawal8184">Pradeep Agrawal</reporter>
                        <labels>
                    </labels>
                <created>Mon, 23 Jun 2014 02:27:34 +0000</created>
                <updated>Sat, 6 Feb 2016 06:41:34 +0000</updated>
                            <resolved>Sat, 6 Feb 2016 06:41:34 +0000</resolved>
                                    <version>3.1.0</version>
                                    <fixVersion>4.0 Backlog</fixVersion>
                                    <component>LDAP</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>3</watches>
                                                                <comments>
                            <comment id="104703" author="pradeepagrawal8184" created="Mon, 23 Jun 2014 02:35:37 +0000"  >&lt;p&gt;if ActiveDirectoryLdapAuthenticationProvider fails then another provider (i.e authentication-provider/jdbc) should work which usage localhost database connection for username/password authentication.&lt;/p&gt;</comment>
                            <comment id="104706" author="rwinch" created="Mon, 23 Jun 2014 06:13:09 +0000"  >&lt;p&gt;If an AuthenticationProvider fails in a way that is unrelated to user interactions (i.e. the LDAP server is down), then it should not continue to try other AuthenticationProvider instances. However, it should be wrapped in an InternalAuthenticationServiceException. See &lt;a href=&quot;https://jira.spring.io/browse/SEC-1919&quot; title=&quot;AuthenticationServiceException logged on DEBUG level&quot; class=&quot;issue-link&quot; data-issue-key=&quot;SEC-1919&quot;&gt;&lt;del&gt;SEC-1919&lt;/del&gt;&lt;/a&gt;&lt;/p&gt;</comment>
                            <comment id="125687" author="issuemaster" created="Sat, 6 Feb 2016 06:25:48 +0000"  >&lt;p&gt;This issue has been migrated to &lt;a href=&quot;https://github.com/spring-projects/spring-security/issues/2884&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://github.com/spring-projects/spring-security/issues/2884&lt;/a&gt;&lt;/p&gt;</comment>
                    </comments>
                    <attachments>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                                            <customfield id="customfield_10170" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>First Response Date</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Mon, 23 Jun 2014 06:13:09 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_10280" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>44556</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_10880" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>0|i07nav:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_10380" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>44647</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_10381" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Ranking</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>44258</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                    <customfield id="customfield_10171" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                </customfields>
    </item>
</channel>
</rss>